name: CI-Train
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Prepare sample data
        run: |
          mkdir -p data/raw
          # Put a tiny CSV so CI can run; replace with your real sample or download step
          printf "target,feat1,feat2\n1,0.1,3\n0,0.2,4\n1,0.3,5\n0,0.4,6\n" > data/raw/sample.csv
      - name: Train
        env:
          DATA_DIR: data
          MODELS_DIR: models
        run: |
          python scripts/train.py
          cat models/metrics.json
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: best-model
          path: models/
